version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # Use Python 3.11
    commands:
      - echo "No dependencies to install. Proceeding with build."

  build:
    commands:
      - echo "Building the To-Do App..."
      - echo "No actual build step required for this CLI app."
      - echo "The app is ready for deployment or further use."

  post_build:
    commands:
      - echo "Build complete. Preparing to upload artifacts."
      - mkdir -p output  # Create the output folder if it doesn't exist
      - cp todo_app.py output/  # Copy your main app script to the output folder
      - echo "Files copied to the output folder."

artifacts:
  files:
    - output/*  # Include everything inside the output folder
  base-directory: '.'  # The root directory of your repository
  discard-paths: yes  # Upload everything as flat files in the S3 folder
  s3:
    bucket: khubbucket  # Replace with your actual bucket name
    key: output/  # The S3 folder where you want the artifacts uploaded
