version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - python --version
      - echo "No dependencies to install. Proceeding with build."

  build:
    commands:
      - echo "Building the To-Do App..."
      - echo "No actual build step required for this CLI app."
      - echo "The app is ready for deployment or further use."

  post_build:
    commands:
      - echo "Build complete. Preparing to upload artifacts."
      - mkdir -p output
      - echo "Output folder created."
      - cp todo_app.py output/
      - echo "Files copied to the output folder."
      - echo "Uploading to S3 bucket khubbucket/output/..."
      - aws s3 cp output/ s3://khubbucket/output/ --recursive
      - echo "Files uploaded to S3."

artifacts:
  files:
    - output/*
  base-directory: '.'
  discard-paths: yes
  s3:
    bucket: khubbucket
    key: output/
