# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       python: 3.11
#     commands:
#       - echo "Installing dependencies..."
#       - python --version
#       - echo "No dependencies to install. Proceeding with build."

#   build:
#     commands:
#       - echo "Building the To-Do App..."
#       - echo "No actual build step required for this CLI app."
#       - echo "The app is ready for deployment or further use."

#   post_build:
#     commands:
#       - echo "Build complete. Preparing to upload artifacts."
#       - mkdir -p output
#       - echo "Output folder created."
#       - cp todo_app.py output/
#       - echo "Files copied to the output folder."
#       - echo "Uploading to S3 bucket khubbucket/output/..."
#       - aws s3 cp output/ s3://khubbucket/output/ --recursive
#       - echo "Files uploaded to S3."

# artifacts:
#   files:
#     - output/*
#   base-directory: '.'
#   discard-paths: yes
#   s3:
#     bucket: khubbucket
#     key: output/

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install pyinstaller==5.11.0  # Install PyInstaller for creating .exe file
      - pip install streamlit==1.16.0    # Install Streamlit for app functionality
      - pip install pytest==7.4.0        # Install Pytest for testing

  pre_build:
    commands:
      - echo Running pre-build checks...
      - python --version
      - pip --version

  build:
    commands:
      - echo Running tests...
      - pytest tests/ --junitxml=report.xml  # Run the tests and generate a report
      - echo Tests completed.
      - echo Building the executable...
      - pyinstaller --onefile todo_app.py  # Replace with your Python script file
      - echo Build complete. Executable created in 'dist' directory.
      - echo Checking if dist folder exists...
      - ls dist || echo "dist folder not found"  # Ensure dist folder exists and print its contents

  post_build:
    commands:
      - echo Preparing artifacts...
      - mkdir -p artifacts  # Ensure the artifacts directory exists
      - echo "Artifacts directory created."
      # Check if dist folder exists and move the executable to artifacts
      - |
        if [ -d "dist" ]; then 
          mv dist/todo_app.exe artifacts/;
          echo "Executable moved to artifacts.";
        else 
          echo "dist folder not found, skipping .exe";
        fi
      # Check if the report file exists and move it to artifacts as well
      - |
        if [ -f "report.xml" ]; then
          mv report.xml artifacts/;
          echo "Report moved to artifacts.";
        else
          echo "report.xml not found, skipping report.";
        fi

      # Debugging: List the contents of the artifacts directory to ensure files are there
      - echo "Listing files in the artifacts directory:"
      - ls -R artifacts/  # List all files and directories in artifacts folder

artifacts:
  files:
    - artifacts/todo_app.exe      # Specify the path to your .exe file in artifacts folder
    - artifacts/report.xml        # Include the test report in the artifacts
  discard-paths: yes
  base-directory: artifacts
s3:
  bucket: khubbucket
  path: artifacts/  # Upload to the existing 'artifacts' folder in your bucket
                 # Store in the 'output' folder in the S3 bucket
